sudo: false
language: python
python: 3.5
install:
- pip install tox coveralls coverage
script:
- ./.travis.script
after_success:
- "COVERAGE_FILE=.coverage coverage combine"
- coveralls
env:
- TOXENV=py34
- TOXENV=py35
- TOXENV=flake8
