name: tox

on: [push, pull_request]

jobs:
  tox:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Pull images
        run: docker-compose -f tests/docker/docker-compose.yml pull
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py
      - name: Run flake8 / docs
        run: tox -e flake8,docs
        if: "matrix.python == '3.10'"
